//
//  AnalysisViewModel.swift
//  Stoic IA
//
//  Main view model coordinating video analysis workflow
//

import Foundation
import SwiftUI
import AVFoundation
import Photos

@MainActor
class AnalysisViewModel: ObservableObject {
    // MARK: - Published Properties

    @Published var analysisResults: [AnalysisResult] = []
    @Published var currentAnalysis: AnalysisResult?
    @Published var isAnalyzing = false
    @Published var analysisProgress: Double = 0.0
    @Published var errorMessage: String?
    @Published var selectedActionType: SoccerAction = .shooting

    // MARK: - Services

    private let visionService = VisionAnalysisService()
    private let analysisEngine = SoccerAnalysisEngine()

    // MARK: - Video Analysis

    func analyzeVideo(url: URL) async {
        isAnalyzing = true
        analysisProgress = 0.0
        errorMessage = nil

        do {
            // Step 1: Extract and analyze frames with Vision (0-50%)
            let videoData = try await visionService.analyzeVideo(at: url)
            analysisProgress = 0.5

            // Step 2: Process with Soccer Analysis Engine (50-100%)
            let result = await analysisEngine.analyzeVideoData(videoData, actionType: selectedActionType)
            analysisProgress = 1.0

            // Create final result with video URL
            let finalResult = AnalysisResult(
                videoURL: url,
                overallScore: result.overallScore,
                techniqueMetrics: result.techniqueMetrics,
                insights: result.insights,
                recommendations: result.recommendations
            )

            currentAnalysis = finalResult
            analysisResults.insert(finalResult, at: 0)

            isAnalyzing = false
        } catch {
            errorMessage = "Analysis failed: \(error.localizedDescription)"
            isAnalyzing = false
            analysisProgress = 0.0
        }
    }

    func selectVideo() {
        // This will be called from the UI to trigger photo picker
    }

    func deleteAnalysis(_ result: AnalysisResult) {
        analysisResults.removeAll { $0.id == result.id }
        if currentAnalysis?.id == result.id {
            currentAnalysis = nil
        }
    }

    func clearAllResults() {
        analysisResults.removeAll()
        currentAnalysis = nil
    }

    // MARK: - Export

    func exportResults(_ result: AnalysisResult) -> String {
        var export = """
        STOIC IA - SOCCER TECHNIQUE ANALYSIS
        =====================================

        Analysis Date: \(result.formattedDate)
        Overall Score: \(String(format: "%.1f", result.overallScore))/100

        TECHNIQUE METRICS
        -----------------
        Ball Control: \(String(format: "%.1f", result.techniqueMetrics.ballControlScore))
        Shooting: \(String(format: "%.1f", result.techniqueMetrics.shootingTechniqueScore))
        Passing: \(String(format: "%.1f", result.techniqueMetrics.passingAccuracyScore))
        Positioning: \(String(format: "%.1f", result.techniqueMetrics.positioningScore))
        First Touch: \(String(format: "%.1f", result.techniqueMetrics.firstTouchScore))

        STRENGTHS
        ---------
        \(result.techniqueMetrics.strengthCategories.isEmpty ? "Focus on building fundamental technique" : result.techniqueMetrics.strengthCategories.joined(separator: ", "))

        AREAS FOR IMPROVEMENT
        ---------------------
        \(result.techniqueMetrics.improvementCategories.joined(separator: ", "))

        PROFESSIONAL INSIGHTS
        ---------------------
        """

        for (index, insight) in result.insights.enumerated() {
            export += """

            \(index + 1). \(insight.title) [\(insight.severity.rawValue)]
               Category: \(insight.category.rawValue)
               Issue: \(insight.description)
               How to Improve: \(insight.improvement)

            """
        }

        export += """

        EXPERT RECOMMENDATIONS
        ----------------------
        """

        for (index, recommendation) in result.recommendations.enumerated() {
            export += "\n\(index + 1). \(recommendation)\n"
        }

        export += """

        =====================================
        Generated by Stoic IA
        Professional Soccer Analysis powered by Apple Intelligence
        """

        return export
    }
}
